### ISSUE TITLE
org.rpm.dnf.v0.rpm.Repo list crash

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1144]
repo_attrs is not well documented, anyway I got from the code the following available attirbutes:

```
"id",
"name",
"type",
"enabled",
"priority",
"cost",
"baseurl",
"metalink",
"mirrorlist",
"metadata_expire",
"cache_updated",
"excludepkgs",
"includepkgs",
"skip_if_unavailable",
"gpgkey",
"gpgcheck",
"repo_gpgcheck",
"proxy",
"proxy_username",
"proxy_password",
"repofile",
"revision",
"content_tags",
"distro_tags",
"updated",
"size",
"pkgs",
"available_pkgs",
"mirrors",
```
i tried all of them and **proxy_password** makes the list method crashing with the following BT:

```
Traceback (most recent call last):
  File "/home/angelo/src/manatools/dnfdragora/../test-dnf5daemon.py", line 225, in <module>
    test()
  File "/home/angelo/src/manatools/dnfdragora/../test-dnf5daemon.py", line 104, in test
    repo_list = iface_repo.list({"repo_attrs": [
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.rpm.dnf.v0.Error: Option value is not set
```

**Comment by ppisar** [comment]
Repository proxy options are not yet fully implemented in D-Bus interface. See repo_to_map():

~~~~
            case RepoAttribute::proxy_username:
                //                dbus_repo.emplace(attr, libdnf_repo->get_config().get_proxy_username_option().get_value());
                dbus_repo.emplace(attr, "user foo");
                break;
            case RepoAttribute::proxy_password:
                dbus_repo.emplace(attr, libdnf_repo->get_config().get_proxy_password_option().get_value());
                break;
~~~~

proxy_username just sends a dummy value and proxy_password attempts to retrieve the value, but get_value() throws an exception if a priority of the option is undefined:

~~~~
const std::string & OptionString::get_value() const {
    if (get_priority() == Priority::EMPTY) {
        //TODO(jrohel): We don't know the option name at this time. Add a text name to the options
        //              or extend exception (add name) in upper layer.
        throw OptionValueNotSetError(M_("Option value is not set"));
    }
    return value;
}
~~~~~

**Comment by ppisar** [comment]
The server actually does not crash. It only forwards the exception over D-Bus, but the daemon survives and continues functioning. What "crashes" is the D-Bus client which receives the exception if it does not handle it.

A reproducer:

~~~~
#!/usr/bin/python3
import dbus
bus = dbus.SystemBus()
manager = bus.get_object('org.rpm.dnf.v0', '/org/rpm/dnf/v0')
manager_iface = dbus.Interface(manager, dbus_interface='org.rpm.dnf.v0.SessionManager')
session = manager_iface.open_session([])
print(session)

repo = bus.get_object('org.rpm.dnf.v0', session)
repo_iface = dbus.Interface(repo, dbus_interface='org.rpm.dnf.v0.rpm.Repo')

try:
    repos = repo_iface.list({'patterns': ['rawhide'], 'repo_attrs': ['proxy_password']})
    print(repos)
except dbus.exceptions.DBusException as error:
    print("An execption occurred: {}".format(error))
    print("Continuing")

repos = repo_iface.list({'patterns': ['rawhide'], 'repo_attrs': ['id']})
print(repos)
~~~~~

The first repo_iface.list() call raises the exception. The latter, with the same sessions replies successfully:

~~~~
# ./ddc 
/org/rpm/dnf/v0/93100d56035d56cb38390fbb11a898e5
An execption occurred: org.rpm.dnf.v0.Error: Option value is not set
Continuing
dbus.Array([dbus.Dictionary({dbus.String('id'): dbus.String('rawhide', variant_level=1)}, signature=dbus.Signature('sv'))], signature=dbus.Signature('a{sv}'))
~~~~~

That the server does not crash can be verified with <code>systemctl status dnf5daemon-server</code>.

**Comment by ppisar** [comment]
By the way, this what dbus-minor shows (different run, different session):

~~~~
method call time=1704718088.701134 sender=:1.80 -> destination=:1.74 serial=7 path=/org/rpm/dnf/v0/2e8e82adc12d20bc9dbc3aed467bde6e; interface=org.rpm.dnf.v0.rpm.Repo; member=list
   array [
      dict entry(
         string "patterns"
         variant             array [
               string "rawhide"
            ]
      )
      dict entry(
         string "repo_attrs"
         variant             array [
               string "proxy_password"
            ]
      )
   ]
error time=1704718088.701586 sender=:1.74 -> destination=:1.80 error_name=org.rpm.dnf.v0.Error reply_serial=7
   string "Option value is not set"
method call time=1704718088.702071 sender=:1.80 -> destination=:1.74 serial=8 path=/org/rpm/dnf/v0/2e8e82adc12d20bc9dbc3aed467bde6e; interface=org.rpm.dnf.v0.rpm.Repo; member=list
   array [
      dict entry(
         string "patterns"
         variant             array [
               string "rawhide"
            ]
      )
      dict entry(
         string "repo_attrs"
         variant             array [
               string "id"
            ]
      )
   ]
method return time=1704718088.702834 sender=:1.74 -> destination=:1.80 serial=28 reply_serial=8
   array [
      array [
         dict entry(
            string "id"
            variant                string "rawhide"
         )
      ]
   ]
~~~~

**Comment by anaselli** [comment]
A silly question that came me already using dnf4 daemon, while setting proxy user and password could be useful, why anyone should/could read it by a  daemon query?
