### ISSUE TITLE
dnfdaemon do_transaction crash

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1187]
It seems that do_transaction does not return. In my test i was installing one package only (atanks)
```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/usr/lib64/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/angelo/src/manatools/dnfdragora/bin/dnfdragora", line 85, in <module>
    main_gui.handleevent()
  File "/home/angelo/src/manatools/venv/lib/python3.10/site-packages/dnfdragora/ui.py", line 1583, in handleevent
    rebuild_package_list = self._manageDnfDaemonEvent()
  File "/home/angelo/src/manatools/venv/lib/python3.10/site-packages/dnfdragora/ui.py", line 2155, in _manageDnfDaemonEvent
    self._OnBuildTransaction(info)
  File "/home/angelo/src/manatools/venv/lib/python3.10/site-packages/dnfdragora/ui.py", line 1991, in _OnBuildTransaction
    self.backend.RunTransaction(sync=True)
  File "/home/angelo/src/manatools/venv/lib/python3.10/site-packages/dnfdragora/dnfd_client.py", line 1237, in RunTransaction
    self._run_dbus_sync('RunTransaction', options)
  File "/home/angelo/src/manatools/venv/lib/python3.10/site-packages/dnfdragora/dnfd_client.py", line 512, in _run_dbus_sync
    return func(*args)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

**Comment by m-blaha** [comment]
Hi, would it be possible to have more details on this? It's not completely clear to me how to reproduce  the issue.

**Comment by anaselli** [comment]
You are right i should have provided a test case. I need to check it again and i'll do. IIRC all the calls that don't return anything had this side effect, but i i'll be more precise after some new tests,

**Comment by anaselli** [comment]
test case:

```
def test_transaction():
    bus = dbus.SystemBus()
    iface_session = dbus.Interface(
        bus.get_object(DNFDAEMON_BUS_NAME, DNFDAEMON_OBJECT_PATH),
        dbus_interface=IFACE_SESSION_MANAGER)

    session = iface_session.open_session({})
    print(f"Open Dnf5Daemon session: {session}")

    iface_base = dbus.Interface(
        bus.get_object(DNFDAEMON_BUS_NAME, session),
        dbus_interface=IFACE_BASE)
    iface_repo = dbus.Interface(
        bus.get_object(DNFDAEMON_BUS_NAME, session),
        dbus_interface=IFACE_REPO)
    iface_rpm = dbus.Interface(
        bus.get_object(DNFDAEMON_BUS_NAME, session),
        dbus_interface=IFACE_RPM)
    iface_goal = dbus.Interface(
        bus.get_object(DNFDAEMON_BUS_NAME, session),
        dbus_interface=IFACE_GOAL)
    iface_repoconf = dbus.Interface(
            bus.get_object(DNFDAEMON_BUS_NAME, session),
            dbus_interface=IFACE_REPOCONF)

    iface_advisory = dbus.Interface(
                bus.get_object(DNFDAEMON_BUS_NAME, session),
                dbus_interface=IFACE_ADVISORY)
    iface_rpm.install(["*btanks*"], {})
    reso, resu = iface_goal.resolve({})
    iface_goal.do_transaction({})
    print("returned correctly press a key")
    s = input()
    session_path = iface_session.close_session(session)

if __name__ == '__main__':
    test_transaction()

```

However now i wrote it down, i have 2 crashes and after that no more once.

```
(Pdb) p resu
dbus.UInt32(0)
(Pdb) iface_goal.do_transaction({})
*** dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

**Comment by papoteur-mga** [comment]
Hello,
after adding 
```
# Get the system bus
DNFDAEMON_BUS_NAME = 'org.rpm.dnf.v0'
DNFDAEMON_OBJECT_PATH = '/' + DNFDAEMON_BUS_NAME.replace('.', '/')

IFACE_SESSION_MANAGER = '{}.SessionManager'.format(DNFDAEMON_BUS_NAME)
IFACE_BASE = '{}.Base'.format(DNFDAEMON_BUS_NAME)
IFACE_REPO = '{}.rpm.Repo'.format(DNFDAEMON_BUS_NAME)
IFACE_REPOCONF = '{}.rpm.RepoConf'.format(DNFDAEMON_BUS_NAME)
IFACE_RPM = '{}.rpm.Rpm'.format(DNFDAEMON_BUS_NAME)
IFACE_GOAL = '{}.Goal'.format(DNFDAEMON_BUS_NAME)
IFACE_ADVISORY = '{}.Advisory'.format(DNFDAEMON_BUS_NAME)
```

I get also:
```
Open Dnf5Daemon session: /org/rpm/dnf/v0/c42531eea9d508715fd71e47cbe92847
Traceback (most recent call last):
  File "/home/yves/dev/dnf-tests/test.py", line 50, in <module>
    test_transaction()
  File "/home/yves/dev/dnf-tests/test.py", line 43, in test_transaction
    reso, resu = iface_goal.resolve({})
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by anaselli** [comment]
> Hello, after adding
> 
> ```
> # Get the system bus
> DNFDAEMON_BUS_NAME = 'org.rpm.dnf.v0'
> DNFDAEMON_OBJECT_PATH = '/' + DNFDAEMON_BUS_NAME.replace('.', '/')
> 
> IFACE_SESSION_MANAGER = '{}.SessionManager'.format(DNFDAEMON_BUS_NAME)
> IFACE_BASE = '{}.Base'.format(DNFDAEMON_BUS_NAME)
> IFACE_REPO = '{}.rpm.Repo'.format(DNFDAEMON_BUS_NAME)
> IFACE_REPOCONF = '{}.rpm.RepoConf'.format(DNFDAEMON_BUS_NAME)
> IFACE_RPM = '{}.rpm.Rpm'.format(DNFDAEMON_BUS_NAME)
> IFACE_GOAL = '{}.Goal'.format(DNFDAEMON_BUS_NAME)
> IFACE_ADVISORY = '{}.Advisory'.format(DNFDAEMON_BUS_NAME)
> ```

You are right. I forgot to add those lines.

To be honest i tested the same code on fedora and i seem i didn't experienced it, while using mageia that often happens

**Comment by papoteur-mga** [comment]
Running it again this morning, I got after some seconds a dialog for root password. It finished OK.
```
Open Dnf5Daemon session: /org/rpm/dnf/v0/11a2fb87ae9951a445f9539bbb94bca5
returned correctly press a key
```

**Comment by m-blaha** [comment]
I've identified a scenario where the do_transaction method can time out.
The first thing handler of this method does is that it checks whether the user is authorized to run rpm transaction. This is done via calling the `CheckAuthorization()` method of the `org.freedesktop.PolicyKit1.Authority` polkit D-Bus interface. For a regular user this should result in showing an authentication dialog. No explicit timeout was set for this call so the default (25 seconds on my Fedora) was used. So in case the user does not enter a password in 25 seconds, the call would time-out. Unfortunately the timeout exception is not caught but is propagated to the client. So from the client side it looks like the `do_transaction` call has timed-out.

Can this explain issues you observed?

**Comment by anaselli** [comment]
it could, we have polkit that ask for a root password instead of the user one as in fedora, then that would explain why after it worked, you are already authenticated for a while...

**Comment by m-blaha** [comment]
Another idea - running a transaction might require importing of the repository PGP key(s) into rpm database. The workflow is roughly:

1. the client calls `Goal.do_transaction()`
2. in case the required key is not present in rpmdb, the server emits the `repo_key_import_request` signal with key details and waits for the response.
3. the client must handle the signal - usually the user is presented with the key details and asked for key import confirmation
4. the client then calls `Repo.confirm_key(key_id, confirmed)` method with the user's answer
5. this unblocks the server and transaction continues

I guess it would be good to document this process and add an example script.

But anyway, by removal of PGP keys from rpmdb I was able to reproduce the timeout issue using the script mentioned in previous comment - https://github.com/rpm-software-management/dnf5/issues/1187#issuecomment-2040382830.

**Comment by anaselli** [comment]
Good to know! I haven't tested how to import gpg key using dnfdragora yet, now i know how to do it:) 
But on this subject is still not the use case i have for experiencing this issue i'm afraid...

**Comment by m-blaha** [comment]
So I have to try harder to find the root cause... :)

**Comment by anaselli** [comment]
you could try to use a mageia VM :D, but i suspect you've been missed some package to build all... if we can provide some logs... but i don't know where to look for...

**Comment by m-blaha** [comment]
I've just tried it... Created mageia cauldron VM (with some hiccups) and build dnf5daemon-server from current github main branch (surprisingly without any problems). But still cannot reproduce the issue.
Regarding logs - you can either check journalctl, or if you run dnf5daemon-server from the command line, you should see all the logs on the console. (Currently dnf5daemon-server just prints messages to stderr)

**Comment by anaselli** [comment]
well mine is a @Conan-Kudo snapshot, so I'm not on current main branch, probably and maybe your fixing is good enough... I'll try your suggestions to see if i can provide anything interesting.
