### ISSUE TITLE
python: cannot set `ResolveSpecSettings`'s `nevra_forms` field

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#1450]
Formally

``` python
import libdnf5

settings = libdnf5.base.ResolveSpecSettings()
settings.nevra_forms.append(libdnf5.rpm.Nevra.Form_NA)
```

allowed changing `nevra_forms` on a `ResolveSpecSettings` object. Now, it seems there's no way to do it.

``` python
import libdnf5

settings = libdnf5.base.ResolveSpecSettings()
settings.set_nevra_forms([libdnf5.rpm.Nevra.Form_NA])
```

fails

``` console
$ python repro.py
Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    settings.set_nevra_forms([libdnf5.rpm.Nevra.Form_NA])
  File "/usr/lib64/python3.12/site-packages/libdnf5/base.py", line 2032, in set_nevra_forms
    return _base.ResolveSpecSettings_set_nevra_forms(self, nevra_forms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'ResolveSpecSettings_set_nevra_forms', argument 2 of type 'std::vector< libdnf5::rpm::Nevra::Form,std::allocator< libdnf5::rpm::Nevra::Form > >'
```

**Comment by kontura** [comment]
Thanks for the report, currently it has to be set like:
```python
settings.set_nevra_forms(libdnf5.rpm.VectorNevraForm(1, libdnf5.rpm.Nevra.Form_NA))
```
We also have it in a test: https://github.com/rpm-software-management/dnf5/blob/main/test/python3/libdnf5/rpm/test_package_query.py#L127-L128

I would like to make it work with the expected: `settings.set_nevra_forms([libdnf5.rpm.Nevra.Form_NA])` but so far I wasn't able to configure SWIG in such a way.

**Comment by gotmax23** [comment]
How do I instantiate `VectorNevraForm` with more than one item?

**Comment by kontura** [comment]
Currently this seems to be possible:
```python
forms = libdnf5.rpm.VectorNevraForm()
forms.push_back(libdnf5.rpm.Nevra.Form_NA)
forms.push_back(libdnf5.rpm.Nevra.Form_NAME)
forms.push_back(libdnf5.rpm.Nevra.Form_NEVRA)
settings.set_nevra_forms(forms)
```

But if you do `settings.get_nevra_forms()` it returns some kind of tuple not the `VectorNevraForm()`.
It needs to be fixed.
