### ISSUE TITLE
Ruby bindings RFE: libdnf5 modules and classes should be namespaced.

### ISSUE THREAD

**Issue by jackorp** [rpm-software-management/dnf5#1779]
While not necessarily a problem, the current lack of namespacing in Ruby does not seem too great to me.

For example `Common` module is a global constant upon requiring `libdnf5/common`. I think having a prefix so that it becomes for example `LibDNF5::Common` (or `Libdnf5::Common`, or other variations of capitalization) would be better.

I'd apply this to all modules present, but names such as `Logger`, `Common`, or `Base` are IMO more probably to have a clash in other projects than for example Rpm.

There could be a small problem with compatibility, but if `LibDNF5` is a module only used for namespacing (with no additional/new methods on it), then it can be included in the global namespace guilt-free:
```ruby
require 'libdnf5/base'
include LibDNF5

base = Base::Base.new()
```

**Comment by jackorp** [comment]
Hmm already ran into a problem with the default Ruby Logger class.

I cannot work with rack and Sinatra gems. since there is a conflict between different Logger constant definitions at the top level if I also `require "libdnf5/base"`.

Simple example:
```console
$ sudo dnf install ruby-libdnf5 rubygem-sinatra
```

And a file `example.rb`
```ruby
#!/usr/bin/ruby
require 'sinatra'
require 'libdnf5/base'

get '/' do
  "Hello"
end
```
When I run `ruby example.rb` to start the server
I get an exception:
```
$ ruby example.rb
/usr/share/ruby/logger/version.rb:3:in `<top (required)>': Logger is not a class (TypeError)
/usr/lib64/ruby/vendor_ruby/libdnf5/logger.so:0: previous definition of Logger was here
	from /usr/share/ruby/logger.rb:17:in `require_relative'
	from /usr/share/ruby/logger.rb:17:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/jprokop/.local/share/gem/ruby/gems/rack-2.2.10/lib/rack/logger.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1741:in `setup_custom_logger'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1723:in `setup_logging'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1711:in `setup_default_middleware'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1559:in `build'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1551:in `new'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1540:in `prototype'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1581:in `start_server'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/base.rb:1522:in `run!'
	from /usr/share/gems/gems/sinatra-3.0.5/lib/sinatra/main.rb:47:in `block in <module:Sinatra>'
```

However I found one problem that might be related, the [`%module` directive in modules](https://github.com/rpm-software-management/dnf5/blob/b0f1caf82fb9f6fdc2c1ea2d3cdcc4661e267aef/bindings/libdnf5/logger.i#L6) gets completely ignored because [CMake files set `-module`](https://github.com/rpm-software-management/dnf5/blob/b0f1caf82fb9f6fdc2c1ea2d3cdcc4661e267aef/bindings/ruby/CMakeLists.txt#L18) which AFAICT overrides that `%module` in file.

On top of that
```
%module "libdnf5/logger"
```
is not a correct module definition.
Swig generates the following kind of code in resulting .cxx file:
```
  mLibdnf5/logger = rb_define_module("Libdnf5/logger");
```
So the `-module` override also hides this issue.
