### ISSUE TITLE
Crashing unit tests - double free or corruption

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#1959]
I have extracted the following with sanitizers:
```
==76263==ERROR: AddressSanitizer: odr-violation (0x00000272d780):
  [1] size=48 'VALID_COMPARATORS' /home/amatej/tmp/src/dnf5/libdnf5/rpm/versionlock_config.cpp:117:54 in /home/amatej/tmp/src/dnf5/container_build/test/dnf5-plugins/copr_plugin/run_tests_copr
  [2] size=48 'VALID_COMPARATORS' /home/amatej/tmp/src/dnf5/libdnf5/rpm/versionlock_config.cpp:117:54 in /home/amatej/tmp/src/dnf5/container_build/libdnf5/libdnf5.so.2
These globals were registered at these points:
  [1]:
    #0 0x7fdb3e41c6f7 in __asan_register_globals.part.0 (/lib64/libasan.so.8+0x1c6f7) (BuildId: ccb4235447d53c438174a52e3672d04596d46000)
    #1 0x9714e5 in _sub_I_00099_1 (/home/amatej/tmp/src/dnf5/container_build/test/dnf5-plugins/copr_plugin/run_tests_copr+0x9714e5) (BuildId: a2190e251a7ab17fafddbd6302dcb65ef4114514)
    #2 0x7fdb33660203 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x4203) (BuildId: 41939f0e8a59632286bf09e69dec833c9f0cc453)
    #3 0x404804 in _start (/home/amatej/tmp/src/dnf5/container_build/test/dnf5-plugins/copr_plugin/run_tests_copr+0x404804) (BuildId: a2190e251a7ab17fafddbd6302dcb65ef4114514)

  [2]:
    #0 0x7fdb3e41c6f7 in __asan_register_globals.part.0 (/lib64/libasan.so.8+0x1c6f7) (BuildId: ccb4235447d53c438174a52e3672d04596d46000)
    #1 0x7fdb3483b0ab in _sub_I_00099_1 (/home/amatej/tmp/src/dnf5/container_build/libdnf5/libdnf5.so.2+0xc3b0ab) (BuildId: 3817ff59898c8d98e77c4a916c0eec2ac7256751)
    #2 0x7fdb3ecdb356 in call_init /usr/src/debug/glibc-2.40.9000-21.fc42.x86_64/elf/dl-init.c:74
    #3 0x7fdb3ecdb356 in call_init /usr/src/debug/glibc-2.40.9000-21.fc42.x86_64/elf/dl-init.c:26
    #4 0x7fdb3ecdb42c in _dl_init /usr/src/debug/glibc-2.40.9000-21.fc42.x86_64/elf/dl-init.c:121
    #5 0x7fdb3ecf361f  (/lib64/ld-linux-x86-64.so.2+0x1d61f) (BuildId: 202b509198e59a1e47fcc34cdacca87d11115cc9)
```

I believe the problem is due to a static variable definition in versionlock_config.cpp and the fact that the tests also statically link with libdnf5.a.

**Comment by ppisar** [comment]
Duplicate of #1893.
