### ISSUE TITLE
DNF5 Python API raises only RuntimeError

### ISSUE THREAD

**Issue by poncovka** [rpm-software-management/dnf5#291]
It looks like the only type of exception raised by the DNF5 Python API is `RuntimeError`.

```
base = libdnf5.base.Base()
query = libdnf5.repo.RepoQuery(base)
query.get()
```

The example above prints the traceback below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/libdnf5/repo.py", line 1779, in get
    return _repo.SackQueryRepoWeakPtr_get(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Query must contain exactly one object.
```

Based on my experiments, this is the only exception type I get no matter what I call, so I guess there is an issue with Python bindings. Luckily, Anaconda installer catches DNF exceptions very early and replaces them with its own set of exceptions, so we shouldn't be affected by this issue too much. However, I am sure there will be projects that won't be happy about this.

**Comment by jan-kolarik** [comment]
This is the relevant block of code in SWIG interface where the mapping is implemented: https://github.com/rpm-software-management/dnf5/blob/5.1.14/bindings/libdnf5/base.i#L25.
